hash-format = "sha256"

[[files]]
file = "config/c2me.toml"
hash = "cdf61af100d8a29e9bbf26cc1b7ad8ae29c82357831705a97bb1dffa8ab386fa"

[[files]]
file = "config/dynamicfps.toml"
hash = "8eac230e722a59915fa26ed453d780cd2034b65ec39a7ffe88135d16840c9692"

[[files]]
file = "config/enhanced_bes.properties"
hash = "84825744a3386b5194422e99eba7a3f49f0b29d4a9eb74a11921fd558d4571e8"

[[files]]
file = "config/entityculling.json"
hash = "bd5d8eaf56e9ddb5196a85a5713db7e213ed88c8895958f33c01464a1cb0a1d3"

[[files]]
file = "config/exordium.json"
hash = "1dc6a3aef057f6d08a802abba3c64af5d604078059787da31d253544c67e8904"

[[files]]
file = "config/fastload.properties"
hash = "08c78ab862dbb711eaa56f41bbf4696e3fe7d7c5882e864bdf6586a0e67234a9"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "1e0ba1e744212f481d857e2c864104eb8853a825f6557874b739763e208f7e59"

[[files]]
file = "config/moreculling.toml"
hash = "459043680fe671f08da4d1a88ff7204fa94880c2a7babba98d68acebc60d49c1"

[[files]]
file = "config/smoothboot.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/sodium-options.json"
hash = "7fa2fdbeb82f6838cdfd4e3c686f31aafba333e505509d75b98883fe8a17f450"

[[files]]
file = "config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "788402a125343b8f538a8415adfda1ee49707fb9349d094030c038447e192649"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4b47562757100608c21dc1440a22175d83b1ebedaebf330c22cc04b951e7a477"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5d55ebf01c451aaad25bf8751de6425c28ff29efe04bd7f46b8863a721234188"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "0e72ac12907f4fb5a499a459cc2c64f9225a0c77ee59e76c9360ff0d3479aea2"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "c2814d761fc227d78759c88c38b37b3985fe4a36d18520a333965a1a9a601c2d"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "18d82b174f61f28a6fcd4d4fe3b29ffa5663a9fabc74314668b6db21430e167c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "be8427f766253fce639d6e3e351b726a9b98e6ebc3ed4bec2023ea352bda0ae8"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "b181531817e2f079d5ac74f78c410d7e978d18c111a81b38a29bb3809102291d"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "82312494cc4cb1b914968097ff27733905e6af5dec5829cdbdbc86e5c05b421e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "74942b197e40ee1a4852751088b911b7ef4b9dd4191c3029896464924a8d8272"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "a358d855d607dde44433097b6a054855143cb2f023f70c23020427b3548b9972"
metafile = true

[[files]]
file = "options.txt"
hash = "2be2b5c10139cacd044848f7ecc86e345ae2d7ae855baeeb1e8e87b4342194eb"
