hash-format = "sha256"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/servercore.toml"
hash = "4f5cd08148f87464a0f5e471787fd609a6546b653845954598e5a240b938a32d"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/options.txt"
hash = "2be2b5c10139cacd044848f7ecc86e345ae2d7ae855baeeb1e8e87b4342194eb"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b21ef031c6ad139361352529cb63f4799ffa91008895e1c7a9a5102ea007ae2d"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "3eb41b1aa6c9cced63bf89e6e3d89af3f47fcc59f964cd4e28d7d9e862c82b6e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "de3c6b57292ba33f190ac6e31b23c3611f3376c5c2a4d5f4e79cd2ccdcb11471"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4f887cad340b79a36fced9ebf72e10eadea29d428087d97125c06067f41e2645"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c0bb895f2240522cc6f20afb9ef46293d9b689b8d46839364350e5b0682bac4b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "88a820c55f782886fbb3d063b1db33d89c924012b20554cd5aec3d27f3ce1819"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9063468d0321798591d5e83044d7e841538b0a6ce8e38a78d415a2461708f45f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "d795ac4bc7321d5b9defa33eaba9e03b5fa38b8345d827417d9366913567cb67"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "0b35eacc51808809894ef78b91dfd614e056a34708e4bd2aa6f5ebeb7993a1c0"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "cfbcb74eec1633a4941c2295cefdf6d1767cd9635494d5e2ec4351728468a3ab"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "b5fa54d30435d38adbbb1918f59a30836783f4cc5fdd55388b80006ceabf3afe"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "d05681b90cd9cf8b424ca4cd295eecbdbfcadf9fd2fc1af612228127fce7a2b6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "e77fe4473df0685a27bdc27f9a50c0dced4d298a2765301c2b1f0b11e078a887"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "ca32a70be2442902d948ea7180ab010a0bf7816e7758b93c1936ca2f814c1a33"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "190d9fd976e99bbb9ba1b52198baf70244756f21d39ff6ba91c235583a0d1209"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true
