hash-format = "sha256"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "4aab6ffc7d48092933083ce1a883ec72827dd6da1ccaae6852154b3e4eaead5d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "ef55a85f0905e41d93de2b7e53266d393bf58f43917d9b15ea8f66b757a5996d"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "c668b4ad565c58243a1e0eb71884b17c77ab2242d983075f12dc2666060709ba"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "5b24c9a57bb6092df95d9e8ec3c79574103967cef4db94508b9b172df1e447e5"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "244a5a217b4604782a66736cae23717c7871acd0e2bbd51dc2b28e4b642885f2"

[[files]]
file = "config/yosbr/options.txt"
hash = "c402465b389607f17ecd45b44d5aef66a3750cef2d1c435189aaf81b667715b8"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ad2380d787eb6ccf4d88e26d646b459fd95b31d76a99f346b60d6dfc7fdc398"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "582070fa54fe1743a837c0351eee7ea4a79080e647d5438656d372ae9433b272"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "4afa048a3c67c71e2dd6ac89d5b77066069a2ecaeee59618020b151a6fa7aab9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "49884f2d7db0e731facf0aa70cf2038dd513624c450cba773a8ca7a47e53953b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d5799cd3b6ea714602c18546b99ba894e7511835b77803304792468fb7ee187"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "dce0df1d0cb1a7f05811ba502f3a3de0458e0c5154f1b72ae493a339f3866083"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "de9842a74bad2677a92f96157171b3108dcacb6a517d395006a1f158d5f46bbb"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f7cda152847b85f770b5130db1e1569b5b86ddf09d399377d7133365922a0e08"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "97156c7cbfd94c3f457f5ef89ab65f1b963b1559f98fd3923ab40cf8cc21a905"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "fe940e70dad29aa8b5e57d9679d7503009d56b1890dbc25194b4d278cbfaae5e"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "509a129f843e72b23f7269fb940bbd757a78716d6f2350f33ebe751c40bb77f8"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "0a6179657082b15117e18fbc80fd60538dc91024a63006e843cb5dbf1991bcbe"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "e77fe4473df0685a27bdc27f9a50c0dced4d298a2765301c2b1f0b11e078a887"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "53e01bde67391ead9e5bcf1e86479aebd9ddb0345f871ce4b49afd655b238523"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2b8076d687072c6a6c5baa1c2dcdab3ce20589c4e473501b9c17f49a6fbe158b"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "a9b1b0bf95c89f2234ed4a19154f7ee6151cc3c57cbc3ce2a2d95eff06db5e60"
metafile = true
