name = "Adrenaline"
author = "SkywardMC"
version = "1.36.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af5a4603cf30733def2124fd2341e40ca2047feeb8af7028ec10c0874dc11ed5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
