name = "Adrenaline"
author = "SkywardMC"
version = "1.36.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed685de73a0ba2e86d5c231b66b749ba9ac8cb190887d85353d4e8b36976ceca"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
