name = "Adrenaline"
author = "SkywardMC"
version = "1.35.2+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19649ff1a00f14272b86b8ddcf0499b5cae86ba283f483d439596daecf5c0c2c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
