name = "Adrenaline"
author = "SkywardMC"
version = "1.35.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43a852c6e1cf977e380c4562ecc782d2d5d375262e00473919f850497f7d8493"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
