name = "Adrenaline"
author = "SkywardMC"
version = "1.25.0+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b48867497939c7ed5ab07f869ae8595b833a031d3361473c338d1aa16ef4ec71"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"
