hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "ab961cf1551e454391a6114e875fa2dfa1a4287a6defe66ae2064c1a36f2e173"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "5a4c8d9a607c15c324a8bca67482ecb3a002dd88aeed332c4fced99268724f81"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "4aab6ffc7d48092933083ce1a883ec72827dd6da1ccaae6852154b3e4eaead5d"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "c668b4ad565c58243a1e0eb71884b17c77ab2242d983075f12dc2666060709ba"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "244a5a217b4604782a66736cae23717c7871acd0e2bbd51dc2b28e4b642885f2"

[[files]]
file = "config/yosbr/options.txt"
hash = "c402465b389607f17ecd45b44d5aef66a3750cef2d1c435189aaf81b667715b8"

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "8958a9efde473f0e9ab49069682c66f5c6cbf8023f983a14658c1a325c7273b7"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "65dc14cadd1ab47573c766f7bf203fe3e4c56554de21b782432f9fa3d66b138c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "a22ba7c148744fe8c1ed7580e95e9a285bd71b2b1c2f66ab9d89c5d43e1498f1"
metafile = true

[[files]]
file = "mods/cull-fewer-leaves.pw.toml"
hash = "1c7a504f7239170935e223fa7bef0f9b4f8df068ccadb71d49a7897c334adb90"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7b83af5380faba6641a6fdf27e239eba79846f6b66a65da810860a8cb1e86ee4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6d88f4cdcc5c08a06c25b83f67bd0e0896d61489ca6b5e508a30a10a00caa7f6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "c5103bd5c497d707072363d1bb994697a62774b8bc79ad5a8c3b33313f824948"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2fb4ce2695c9f6da2087a5e350f2e85ea419de153e18bc20bf38f0b540c7caba"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "67116d1cf5d38dfd27aded9d675afcc625d720a4d457660ff82db760934d9f4d"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "51c5dc79381f5e788aa78211c82a8294ec8b1313a5f8cc584fba1e62664dea81"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "4e8594e405f040e73813e5dbb0eb0d5f0f326f8ba07b27f2e8698b22598aa94e"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "c8797508817203139598e45c3249c08bef98d913082d3adb7ce07a6c55e8bdb5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0b4c98b7b25cdfcbb7882c32155d597f0fcaa37aa301b14baf4ad8cab65fea85"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "62b351fa55e61a36efa5530ea2dcbbbf8662ac791e42656fc28cef6d6918e623"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "4dd22192db66cc2819ec1ebae733de139d1d34fddfd0c7166e8dccd1098d5386"
metafile = true
