name = "Adrenaline"
author = "SkywardMC"
version = "1.35.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9abc56d509f62eeab0facc04ae6a2853db9fd55813a785f1db4033cbfff12425"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
