name = "Adrenaline"
author = "SkywardMC"
version = "1.35.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ccce8a6f1a37ed1ac2075d3fe525c609fe0830bed987e429ea3b20b7b932626"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
