name = "Adrenaline"
author = "SkywardMC"
version = "1.32.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4205908e318adaffeedb2a2c65ba9c79c616b714e42b6850c39855ed2db3f04e"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
