name = "Adrenaline"
author = "SkywardMC"
version = "1.32.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2a83121fe48fbe9d96a0440358ba0c7b18b050467ca1996a8f0129d1d8a94e5"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
