name = "Adrenaline"
author = "SkywardMC"
version = "1.35.2+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfb1890a4e1c818292fb2ce4eddd80b81e6e5887019ae3c891ea075d2b52becd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
