name = "Adrenaline"
author = "SkywardMC"
version = "1.32.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33eeb93b417f503826aa0eced956341b5e9b655ff6273b223c3b66b1de5a344d"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
