hash-format = "sha256"

[[files]]
file = "config/c2me.toml"
hash = "694a9224e352a6f7c769a1a95b95eca1ae3151c35bc6d0992cee813214e3b8b4"

[[files]]
file = "config/entityculling.json"
hash = "d1263f28704a153ad67c648fe20b37ab8c9d65f279b2130d29a4ce8be8ad9d0a"

[[files]]
file = "config/exordium.json"
hash = "b2caa9c1a2ff986d6f1816371c44989ffc7c0336f91475b9a6fcdc61fae9ef40"

[[files]]
file = "config/fastload.properties"
hash = "68939002351c5387d6576c404146e966d00d41f32bee099e850f05481236f1a2"

[[files]]
file = "config/ferritecore.mixin.properties"
hash = "1e0ba1e744212f481d857e2c864104eb8853a825f6557874b739763e208f7e59"

[[files]]
file = "config/moreculling.toml"
hash = "1df79f42a4c548bc86da79459085a06d2366b18e5bf26502f47d4048a9212d0e"

[[files]]
file = "config/sodium-options.json"
hash = "f2491c17a592a456453a04c9d99ca53d5ad3dfd2dd797a18ad2bd210d24d5d87"

[[files]]
file = "config/tr7zwDonorSettings.json"
hash = "accf3ae12dbb30c807b81d59a5310784aef56bb992cbd287fd6117aaf144fcff"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "01ab4442937c2d1f582722d139c0d02b3fc36c61a3eeebb4e81bd5256b7d8470"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "81a389a5035dc0852ce12c796f1d667bb4715b1d6ffde16433bf80f02e3796bc"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "ed622deb60304758f1f8ee69e33f057b2d95ab1b65cddc4218978e9255814b77"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5153b742252cd104d2fd71eea311d7523ba1b808ef832f1b8a9b7ede7c12a6e2"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "a5c59c3e730a90d86c9fcc59a36eeed58235826cd6630d208dd1422b3d4f0727"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3d3aeba8c78ad473c8064334c2b4d1c52cfc514640b3c03a00b66e0552f21967"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "998f45a9037fa4663bc5e2bea5de925bf4ce6352328fcaaa830db8466cc62416"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "3ffe2388740cc111a332082f56e37bb4b95764035dfe5d6dff81db8a35d4cc4d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "77e9a02e09ec5a0d6682e5f448953048d99e36da299d92627044aff0828798e3"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "4716789e4a806c1cabcef27e67150215edb4c3d737e9a87d90f2f615d6c196cd"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "741381be667a7b124ce60ba17fca9207369bd6ead4e58ce64fa140aff95f8159"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "fc45b583ec8ca686b666c2cdaaab32c2dc013ce491bfbffa4b5fc20b4c758a70"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "64a7d2034f46aa465709d7af2ff7771f632d03516d6f2897a942fd5fd8145fb2"
metafile = true

[[files]]
file = "options.txt"
hash = "fefbfc8eb13fbc46b2f46d40237cba601ba23f31b77e62e6a82eff8ea6644708"
