hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "ab961cf1551e454391a6114e875fa2dfa1a4287a6defe66ae2064c1a36f2e173"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "232f96c44e7259e2efcf46051380998a472e18baa9afd1a43df914abae66948b"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "4aab6ffc7d48092933083ce1a883ec72827dd6da1ccaae6852154b3e4eaead5d"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "633e40d4d0297b1388f92877424ac1966077b9e3337096c425711a8683abb050"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "244a5a217b4604782a66736cae23717c7871acd0e2bbd51dc2b28e4b642885f2"

[[files]]
file = "config/yosbr/options.txt"
hash = "c402465b389607f17ecd45b44d5aef66a3750cef2d1c435189aaf81b667715b8"

[[files]]
file = "mods/better-block-entities.pw.toml"
hash = "c8d6bda044475105c02984665f1205537241931d927f825cd8af9699264c1025"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "97e98555e9abfc88913c5e40180e466c5fcb51a62706f43880c25b954d16c700"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "a22ba7c148744fe8c1ed7580e95e9a285bd71b2b1c2f66ab9d89c5d43e1498f1"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0cadf1632a675a92e0bbfb060e807c07595bda05526da8a361d782878b510e6b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "b730fc28c1b70d3304d81dd26e7dd1af73f3486d5979f8cec7af5dbb9588a936"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "19b5a6351ca8f850ddb22e07cdae9d83138aaff17a75b21c88b6e0a2b4fb530a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "e27ebce7267fbba8f0216424b21f041bc6c77a773d71848963c41d7a93e02c51"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "db46aeba51086f72e755106ca1a2196717ddb3844dfd7b781e7a93c57a9d5b32"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2fb4ce2695c9f6da2087a5e350f2e85ea419de153e18bc20bf38f0b540c7caba"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "84ca48611902643c3934139e0dce480294b2f2e891cf797fede0607d5b9f6dfa"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "6e950bf32b4589d8c966b9e6a2a0a268000897db09dc093f0cabd0ea77bb95a6"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "4e8594e405f040e73813e5dbb0eb0d5f0f326f8ba07b27f2e8698b22598aa94e"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "886b70d966a36dca61cbd19c4d3955ed657206ce9b8491aad7894c0a369355cd"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "55357dc2a4600d1d41da56e732cea49fae96b4975c4be4ac8fc89a38dff7d958"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zfastnoise.pw.toml"
hash = "a7ab6a121ae62579dde4bcf2cad941a24a77991fcf9e8685ed29eaf3c332fd6a"
metafile = true
