name = "Adrenaline"
author = "SkywardMC"
version = "1.32.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "219e0b91268c2bce7eaa9807d517ef463e856aed3f0cbf0d49e539053155f67b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
