name = "Adrenaline"
author = "SkywardMC"
version = "1.35.2+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3357c4da167c33cdf2886a1587d87301ef96cd22489eea5e8339f7a2380cdd98"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
