name = "Adrenaline"
author = "SkywardMC"
version = "1.35.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df923ca51012085a2ecbbf8a1114b7d3398f1130b6c3fac63c62cca0c0928456"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
