name = "Adrenaline"
author = "SkywardMC"
version = "1.33.1+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "286aa70632b1f8e3c8474d43d97caceb980d536fb7e7cb890ac5f1f0726907c7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
