name = "Adrenaline"
author = "UltraStorm"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff5d617fbbf222daa502ff5e98ceb2404538cd9a2e03dcf2eb50efc7b05c389b"

[versions]
fabric = "0.14.8"
minecraft = "1.17.1"
