hash-format = "sha256"

[[files]]
file = "config/yosbr/config/c2me.toml"
hash = "cdf61af100d8a29e9bbf26cc1b7ad8ae29c82357831705a97bb1dffa8ab386fa"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "8eac230e722a59915fa26ed453d780cd2034b65ec39a7ffe88135d16840c9692"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "84825744a3386b5194422e99eba7a3f49f0b29d4a9eb74a11921fd558d4571e8"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "bd5d8eaf56e9ddb5196a85a5713db7e213ed88c8895958f33c01464a1cb0a1d3"

[[files]]
file = "config/yosbr/config/exordium.json"
hash = "1dc6a3aef057f6d08a802abba3c64af5d604078059787da31d253544c67e8904"

[[files]]
file = "config/yosbr/config/fastload.properties"
hash = "08c78ab862dbb711eaa56f41bbf4696e3fe7d7c5882e864bdf6586a0e67234a9"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1e0ba1e744212f481d857e2c864104eb8853a825f6557874b739763e208f7e59"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "39e289b38f9dab390f1103490002374eaf98c688de33cf6abf1e72dc9a5b9c92"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "459043680fe671f08da4d1a88ff7204fa94880c2a7babba98d68acebc60d49c1"

[[files]]
file = "config/yosbr/config/smoothboot.json"
hash = "c37edec3875da8e561eb60bb7a18dcdce128cc41cfe26261c65a8e942f65d58f"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "7fa2fdbeb82f6838cdfd4e3c686f31aafba333e505509d75b98883fe8a17f450"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "94b8f5236dd7488d6851256816c2edaaaf7224a2be1f7337d554a1eabe475e7f"

[[files]]
file = "config/yosbr/options.txt"
hash = "c2ac066c7543e2228d8b2331f993aec6a586f25f988725bf7d555204a2dca330"

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7227ae7ebc90974368b355d80fd7e6bf76e7fe9946237e8cbc9a3f43f3488b0f"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "61c72ce5be0869a31c41c078961e451b82724e09e617ea0fb85c91be9e09b892"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "cc62c39be7b1e92038627ee2d8157b3e96d020aed56957327c1324c3419bad37"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f694e5041866e133c16c2777e98b643011432b0bd8d97f2666722f3758fd8b2d"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "51c317a3ab72589f7f7856a15421f6a52fe2fc73eb81a1b3dd3269dc92252262"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "1629bdab584c04d02ac3da81340e0d48b611b6ac6044d677fcdc32d4ba4a4da2"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "ea127e8f74006f3a9ce099f9e96adaa3b3f4f281231ece703c4e7f9732137ebd"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "cfff77a6b3c6fd42810c9e2b10e5243258b4949f3935e9e0708f65aed580360c"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "6cf72540c65ecc6586c24bb0f7f51f4c8668bafa384c9c762a03d9e69a434860"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "082d202257610559228e6bea1d1068fe25eba87c306dc4142e874f118ac8949f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dfae39183ee753bc76f63d9c2770b3b92297b028b9437185fc822891c4bb621a"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true
