name = "Adrenaline"
author = "SkywardMC"
version = "1.33.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ce1049df7e2ad84218cc577247814d42abb81c16b4167b3cdd140a633beb83c"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
