name = "Adrenaline"
author = "SkywardMC"
version = "1.35.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4e0be6308bacdc7976a6a25a27e180a3146d858dd80a21c8ebb7d363ec6d73a"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
